logging:
  level:
    root: INFO

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

#eureka:
#  client:
#    service-url:
#      default-zone: ${REGISTRY_SERVICE_URL}
#    healthcheck:
#      enabled: true
#  instance:
#    lease-expiration-duration-in-seconds: 2
#    lease-renewal-interval-in-seconds: 1

server:
  port: ${PORT}