INSERT INTO assessment (name) VALUES
    ('PROPOSAL_PRESENTATION'),
    ('PROGRESS_REPORT'),
    ('ADVISOR_ASSESSMENT'),
    ('FINAL_REPORT'),
    ('FINAL_PRESENTATION');

INSERT INTO level (name, weight) VALUES
    ('BEGINNING',       1),
    ('DEVELOPING',      2),
    ('ACCOMPLISHED',    3),
    ('EXEMPLARY',       4);

INSERT INTO topic (name, assessment_id, weight) VALUES
    ('Project objectives/Expected outcomes', (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION'), 10),
    ('Cite recent developments pertaining to an engineering field', (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION'), 20),
    ('Develop functional requirements by analyzing desired needs', (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION'), 20),
    ('Develop technical and non-technical constraints', (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION'), 10),
    ('Solution specifications', (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION'), 15),
    ('Future work plan', (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION'), 10),
    ('Oral expression', (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION'), 10),
    ('Slides quality', (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION'), 5),

    ('Meeting management', (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT'), 20),
    ('Proposal report', (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT'), 20),
    ('Progress report', (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT'), 20),
    ('Proposed solution and implementation progress', (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT'), 20),
    ('Motivation/initiative/creativity', (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT'), 20),

    ('Acquire and apply new knowledge as needed, using appropriate learning strategies (7.1)',
        (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT'), 20),
    ('Function effectively on a team whose members together provide leadership, create a collaborative and inclusive environment, establish goals, plan tasks, and meet objectives (5.1)',
        (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT'), 20),
    ('Skills for engineering practice',
        (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT'), 20),
    ('Objectives/Achievement',
        (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT'), 20),
    ('Motivation/initiative/creativity/Meeting management',
        (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT'), 20),

    ('Project objectives/Outcomes',
        (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 10),
    ('Background research/Related works',
     (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 10),
    ('Develop functional requirements by analyzing desired needs (2.1)',
         (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 10),
    ('Develop technical and non-technical constraints (2.2)',
        (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 10),
    ('Problem formulation',
        (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 10),
    ('Incorporate appropriate engineering standards and specifications related to the engineering design (2.3)',
        (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 10),
    ('Propose multiple solutions and evaluate them against functional requirements and constraints (2.4)',
        (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 10),
    ('Implement, test and iteratively improve a solution satisfying the specified functional requirements and constraints, considering risks, and making trade-offs (2.5)',
        (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 5),
    ('Results presentation and analysis',
        (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 5),
    ('Conclusion and perspectives',
        (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 5),
    ('Make informed judgments by considering the impact of engineering solutions in global, economic, environmental and societal contexts (4.2)',
        (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 5),
    ('Demonstrate written communication skills with a range of audience by writing adequate documents using appropriate format and language (3.1)',
        (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 5),
    ('Scientific referencing',
        (SELECT id FROM assessment WHERE name = 'FINAL_REPORT'), 5),

    ('Project objectives/Outcomes',
        (SELECT id FROM assessment WHERE name = 'FINAL_PRESENTATION'), 10),
    ('Background research/Related works',
        (SELECT id FROM assessment WHERE name = 'FINAL_PRESENTATION'), 10),
    ('Develop functional requirements by analyzing desired needs (2.1)',
        (SELECT id FROM assessment WHERE name = 'FINAL_PRESENTATION'), 10),
    ('Develop technical and non-technical constraints (2.2)',
        (SELECT id FROM assessment WHERE name = 'FINAL_PRESENTATION'), 10),
    ('Propose multiple solutions and evaluate them against functional requirements and constraints (2.4)',
        (SELECT id FROM assessment WHERE name = 'FINAL_PRESENTATION'), 10),
    ('Implement, test and iteratively improve a solution satisfying the specified functional requirements and constraints, considering risks, and making trade-offs (2.5)',
        (SELECT id FROM assessment WHERE name = 'FINAL_PRESENTATION'), 10),
    ('Results and analysis',
        (SELECT id FROM assessment WHERE name = 'FINAL_PRESENTATION'), 10),
    ('Conclusion and perspectives',
        (SELECT id FROM assessment WHERE name = 'FINAL_PRESENTATION'), 10),
    ('Demonstrate oral communication skills with a range of audience by using appropriate verbal and non-verbal language, adopting the appropriate formatting and supporting material (3.2)',
        (SELECT id FROM assessment WHERE name = 'FINAL_PRESENTATION'), 10),
    ('Slides quality',
        (SELECT id FROM assessment WHERE name = 'FINAL_PRESENTATION'), 10);

-- PROPOSAL_PRESENTATION
INSERT INTO rubric (description, topic_id, level_id) VALUES
 ('Students presented all the objectives of the project and set out all the outcomes with justification.',
  (SELECT id FROM topic WHERE name LIKE '%Project objectives/Expected outcomes%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students presented the main objectives of the project and identified the main outcomes.',
  (SELECT id FROM topic WHERE name LIKE '%Project objectives/Expected outcomes%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students presented some of the objectives of the project or identified marginal outcomes.',
  (SELECT id FROM topic WHERE name LIKE '%Project objectives/Expected outcomes%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students did not present the objectives of the project and did not identify any outcome.',
  (SELECT id FROM topic WHERE name LIKE '%Project objectives/Expected outcomes%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students cited recent developments pertaining to an engineering field and analysed the relation with the project topic.',
  (SELECT id FROM topic WHERE name LIKE '%Cite recent developments pertaining to an engineering field%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students cited recent developments pertaining to an engineering field related to the project topic.',
  (SELECT id FROM topic WHERE name LIKE '%Cite recent developments pertaining to an engineering field%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students cited recent developments irrelevant to the project topic.',
  (SELECT id FROM topic WHERE name LIKE '%Cite recent developments pertaining to an engineering field%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students did not cite any recent developments.',
  (SELECT id FROM topic WHERE name LIKE '%Cite recent developments pertaining to an engineering field%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students developped functional requirements of the project and analysed their dependencies and organized them by priority.',
  (SELECT id FROM topic WHERE name LIKE '%Develop functional requirements by analyzing desired needs%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students developped functional requirements of the project.',
  (SELECT id FROM topic WHERE name LIKE '%Develop functional requirements by analyzing desired needs%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students developped an incomplete set of functional requirements of the project.',
  (SELECT id FROM topic WHERE name LIKE '%Develop functional requirements by analyzing desired needs%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students did not develop any functional requirements.',
  (SELECT id FROM topic WHERE name LIKE '%Develop functional requirements by analyzing desired needs%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students developed non-technical and measurable technical constraints of the project and related them to functional requirements.',
  (SELECT id FROM topic WHERE name LIKE '%Develop technical and non-technical constraints%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students developed non-technical and measurable technical constraints of the project',
  (SELECT id FROM topic WHERE name LIKE '%Develop technical and non-technical constraints%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students developed incomplete non-technical and technical constraints of the project',
  (SELECT id FROM topic WHERE name LIKE '%Develop technical and non-technical constraints%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students did not develop any constraints.',
  (SELECT id FROM topic WHERE name LIKE '%Develop technical and non-technical constraints%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students provided detailed solution specification for the project supported by models and representation (flowcharts, diagrams, etc.).',
  (SELECT id FROM topic WHERE name LIKE '%Solution specifications%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students provided solution specification for the project.',
  (SELECT id FROM topic WHERE name LIKE '%Solution specifications%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students provided incomplete solution specification for the project.',
  (SELECT id FROM topic WHERE name LIKE '%Solution specifications%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students did not provide solution specification for the project.',
  (SELECT id FROM topic WHERE name LIKE '%Solution specifications%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students presented a detailed plan for their future work, covering time and resources (software/hardware, etc.) supported by risk management.',
  (SELECT id FROM topic WHERE name LIKE '%Future work plan%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students provided a detailed plan for their future work covering time and resources.',
  (SELECT id FROM topic WHERE name LIKE '%Future work plan%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students provided an incomplete work plan (in terms of time, resources, risk management) for their future work.',
  (SELECT id FROM topic WHERE name LIKE '%Future work plan%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students did not provide a plan for their future work.',
  (SELECT id FROM topic WHERE name LIKE '%Future work plan%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students made use of relevant semantics supported by a coherent speech and apporpriate body language.',
  (SELECT id FROM topic WHERE name LIKE '%Oral expression%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students made use of relevant semantics supported by a coherent speech.',
  (SELECT id FROM topic WHERE name LIKE '%Oral expression%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students made use of relevant semantics.',
  (SELECT id FROM topic WHERE name LIKE '%Oral expression%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students made use of irrelevant semantics and incoherent speech.',
  (SELECT id FROM topic WHERE name LIKE '%Oral expression%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Slides followed a structured outline with a proper layout (density, numbering, header/footer, etc.), pertinent verbal transitions and an adpated design.',
  (SELECT id FROM topic WHERE name LIKE '%Slides quality%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Slides followed a structured outline with a proper layout (density, numbering, header/footer, etc.).',
  (SELECT id FROM topic WHERE name LIKE '%Slides quality%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Slides followed an unstructured outline, or had an improper layout (density, numbering, header/footer, etc.).',
  (SELECT id FROM topic WHERE name LIKE '%Slides quality%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Slides followed unstructured outline and had an improper layout (density, numbering, header/footer, etc.).',
  (SELECT id FROM topic WHERE name LIKE '%Slides quality%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROPOSAL_PRESENTATION')),
  (SELECT id FROM level WHERE name = 'BEGINNING'));

-- PROGRESS_REPORT
INSERT INTO rubric (description, topic_id, level_id) VALUES
 ('Self-initiated regular meetings (minimum two per month). Minutes of meetings are regularly submitted, template is respected, and all relevant information is covered.',
  (SELECT id FROM topic WHERE name LIKE '%Meeting management%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Regular meetings (minimum two per month). Minutes of meetings are regularly submitted, template is respected, and all relevant information is covered.',
  (SELECT id FROM topic WHERE name LIKE '%Meeting management%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('No regular meetings. Inappropriate minutes of meeting (template is not respected, minimum effort is done to cover meetings topics and guidelines and to submit minutes regularly).',
  (SELECT id FROM topic WHERE name LIKE '%Meeting management%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('No regular meetings. Missing minutes of meeting.',
  (SELECT id FROM topic WHERE name LIKE '%Meeting management%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Report respects template and deadline. All items are covered with a high level of relevant details.',
  (SELECT id FROM topic WHERE name LIKE '%Proposal report%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Report respects template and deadline. All items are covered.',
  (SELECT id FROM topic WHERE name LIKE '%Proposal report%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Report respects template and deadline, but minimal effort is done to cover important items.',
  (SELECT id FROM topic WHERE name LIKE '%Proposal report%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Missing or inappropriate proposal report. It does not respect template, and is not submitted on time.',
  (SELECT id FROM topic WHERE name LIKE '%Proposal report%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Report respects template and deadline. All items are covered with a high level of relevant details.',
  (SELECT id FROM topic WHERE name LIKE '%Progress report%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Report respects template and deadline. All items are covered.',
  (SELECT id FROM topic WHERE name LIKE '%Progress report%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Report respects template and deadline, but minimal effort is done to cover important items.',
  (SELECT id FROM topic WHERE name LIKE '%Progress report%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Missing or inappropriate progress report. It does not respect template, and is not submitted on time.',
  (SELECT id FROM topic WHERE name LIKE '%Progress report%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students proposed a suitable solution incorporating appropriate engineering standards and provided an implementation respecting the solution specification and validated by tests.',
  (SELECT id FROM topic WHERE name LIKE '%Proposed solution and implementation progress%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students proposed a suitable solution incorporating appropriate engineering standards and provided an implementation respecting the solution specification.',
  (SELECT id FROM topic WHERE name LIKE '%Proposed solution and implementation progress%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students proposed a suitable solution incorporating appropriate engineering standards but did not provide any implementation.',
  (SELECT id FROM topic WHERE name LIKE '%Proposed solution and implementation progress%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('No solution was proposed.',
  (SELECT id FROM topic WHERE name LIKE '%Proposed solution and implementation progress%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students were motivated during the project. They took initiative, made their own decisions, and came up with new and creative ideas, propositions, and solutions.',
  (SELECT id FROM topic WHERE name LIKE '%Motivation/initiative/creativity%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students showed motivation for their project. They were able to take initiatives to make their work advance.',
  (SELECT id FROM topic WHERE name LIKE '%Motivation/initiative/creativity%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students showed little/unstable motivation. Little initiative has been taken.',
  (SELECT id FROM topic WHERE name LIKE '%Motivation/initiative/creativity%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students were passive with no motivation. They did not take any initiative in their work.',
  (SELECT id FROM topic WHERE name LIKE '%Motivation/initiative/creativity%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'PROGRESS_REPORT')),
  (SELECT id FROM level WHERE name = 'BEGINNING'));

-- ADVISOR_ASSESSMENT
INSERT INTO rubric (description, topic_id, level_id) VALUES
 ('Students acquired and applied relevant new knowledge autonomously using appropriate learning strategies',
  (SELECT id FROM topic WHERE name LIKE '%Acquire and apply new knowledge as needed, using appropriate learning strategies (7.1)%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students acquired and applied relevant new knowledge with guidance.',
  (SELECT id FROM topic WHERE name LIKE '%Acquire and apply new knowledge as needed, using appropriate learning strategies (7.1)%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students acquired new knowledge but were not able to apply it.',
  (SELECT id FROM topic WHERE name LIKE '%Acquire and apply new knowledge as needed, using appropriate learning strategies (7.1)%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students did not acquire new knowledge.',
  (SELECT id FROM topic WHERE name LIKE '%Acquire and apply new knowledge as needed, using appropriate learning strategies (7.1)%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students collaborated with team members of different backgrounds, in order to establish goals, plan tasks, and meet objectives by using collaborative tools.',
  (SELECT id FROM topic WHERE name LIKE '%Function effectively on a team whose members together provide leadership, create a collaborative and inclusive environment, establish goals, plan tasks, and meet objectives (5.1)%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students collaborated with team members of different backgrounds, in order to establish goals, plan tasks, and meet objectives.',
  (SELECT id FROM topic WHERE name LIKE '%Function effectively on a team whose members together provide leadership, create a collaborative and inclusive environment, establish goals, plan tasks, and meet objectives (5.1)%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students collaborated with team members of different backgrounds, in order to establish goals, plan tasks, but did not meet objectives.',
  (SELECT id FROM topic WHERE name LIKE '%Function effectively on a team whose members together provide leadership, create a collaborative and inclusive environment, establish goals, plan tasks, and meet objectives (5.1)%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students did not establish goals, plan tasks, and meet objectives.',
  (SELECT id FROM topic WHERE name LIKE '%Function effectively on a team whose members together provide leadership, create a collaborative and inclusive environment, establish goals, plan tasks, and meet objectives (5.1)%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students showed advanced skills necessary for engineering practice (such as programming, drawing and manipulating equipment).',
  (SELECT id FROM topic WHERE name LIKE '%Skills for engineering practice%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students showed skills necessary for engineering practice of the project (such as programming, drawing and manipulating equipment).',
  (SELECT id FROM topic WHERE name LIKE '%Skills for engineering practice%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students showed limited skills necessary for engineering practice (such as programming, drawing and manipulating equipment).',
  (SELECT id FROM topic WHERE name LIKE '%Skills for engineering practice%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students showed no skills necessary for engineering practice (such as programming, drawing and manipulating equipment).',
  (SELECT id FROM topic WHERE name LIKE '%Skills for engineering practice%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students were able to attain the expected objectives and tackled additional ones.',
  (SELECT id FROM topic WHERE name LIKE '%Objectives/Achievement%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students attained the expected objectives.',
  (SELECT id FROM topic WHERE name LIKE '%Objectives/Achievement%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students did not attain all expected objectives.',
  (SELECT id FROM topic WHERE name LIKE '%Objectives/Achievement%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students failed to attain the main objectives.',
  (SELECT id FROM topic WHERE name LIKE '%Objectives/Achievement%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'BEGINNING')),

 ('Students were motivated during the project. They took initiative, made their own decisions, and came up with new and creative ideas, propositions, and solutions. They had Self-initiated regular meetings (minimum two per month). Minutes of meetings are regularly submitted, template is respected, and all relevant information is covered.',
  (SELECT id FROM topic WHERE name LIKE '%Motivation/initiative/creativity/Meeting management%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'EXEMPLARY')),
 ('Students showed motivation for their project. They were able to take initiatives to make their work advance. They had Regular meetings (minimum two per month). Minutes of meetings are regularly submitted, template is respected, and all relevant information is covered.',
  (SELECT id FROM topic WHERE name LIKE '%Motivation/initiative/creativity/Meeting management%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'ACCOMPLISHED')),
 ('Students showed little/unstable motivation. Little initiative has been taken. They had No regular meetings. Inappropriate minutes of meeting (template is not respected, minimum effort is done to cover meetings topics and guidelines and to submit minutes regularly).',
  (SELECT id FROM topic WHERE name LIKE '%Motivation/initiative/creativity/Meeting management%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'DEVELOPING')),
 ('Students were passive with no motivation. They did not take any initiative in their work. They had No regular meetings. Missing minutes of meeting.',
  (SELECT id FROM topic WHERE name LIKE '%Motivation/initiative/creativity/Meeting management%' AND assessment_id = (SELECT id FROM assessment WHERE name = 'ADVISOR_ASSESSMENT')),
  (SELECT id FROM level WHERE name = 'BEGINNING'));